require("dotenv").config();

const Telegrambot = require('node-telegram-bot-api');

const bot = new Telegrambot(process.env.BOT_TOKEN, { polling: true });

const options = {
    caption: "Welcome! @@NAME@@!\n"
        + "Aglippa, the ultimate AI Meme Community!\n"
        + "Discover, create, and share hilarious memes generated by advanced AI technology.\n"
        + "Be a part of the next big thing in meme culture.",
    reply_markup: JSON.stringify({
        inline_keyboard: [
            [{ text: '🎮 Play Aglippa!', web_app: { url: 'https://aglippa-dev.io.pe.kr' } }],
            [{ text: '📜 Aglippa Narative', url: 'https://www.aglippa.xyz' }],
            [{ text: '🏆 Meme Contest', url: 'https://forms.gle/cPdQA6pbCoCpmmG18' }],
            [{ text: '💬 Join Chat!', url: 't.me/aglippa_chat' }]
        ]
    })
};

bot.onText(/\/start/, (msg) => {
    const _chatId = msg.chat.id;
    //console.log('msg:', msg);
    options.caption = options.caption.replace('@@NAME@@', msg.chat.first_name);
    bot.sendAnimation(_chatId,
        proccess.env.BOT_ANIMATION,
        options
    );
    //bot.sendPhoto();
    //bot.sendMessage(chatId, "", options);
});

